### PR TITLE
pr commit

### PR DESCRIPTION
**Pull request by StarSheriff2**

### CODE REVIEW

**Comment by smunozmo** [comment]
Hi @StarSheriff2 ,

Your code looks great, there are some changes that could improve your code: 🚀

https://github.com/StarSheriff2/todo-list-code-review/blob/2d25e9896273f6312afa09e520aec7d09570de62/src/lib/task_status.js#L5-L12

This block code could use a function to keep it DRY.

That's it, your code looks great, happy coding! 🤓

**Comment by StarSheriff2** [comment]
> Hi @StarSheriff2 ,
> 
> Your code looks great, there are some changes that could improve your code: 🚀
> 
> https://github.com/StarSheriff2/todo-list-code-review/blob/2d25e9896273f6312afa09e520aec7d09570de62/src/lib/task_status.js#L5-L12
> 
> This block code could use a function to keep it DRY.
> 
> That's it, your code looks great, happy coding! 🤓

Thanks for the feedback. That is true. I think this section could be improved with a function.

**Comment by StarSheriff2** [comment]
I just made the requested change. Let me know if that makes the code drier.

This is how it looks now:

https://github.com/StarSheriff2/todo-list-code-review/blob/fa4c2932aaa369660530359b128b216883530172/src/lib/task_status.js#L3-L18

**Comment by smunozmo** [comment]
It looks perfect, you are a refactor master now @StarSheriff2.

There's nothing else to say, time to merge it!


https://user-images.githubusercontent.com/83717285/126337109-0502ba2e-13dd-44d8-ac12-a9eb0f94d137.mp4



Happy coding! 🤓

**Pull request merged**
